version: "3.1"
services:
  api:
    # replace username/repo:tag with your name and image details
    image: snaekomu/vuores-ar-backend:0.1.1
    container-name: api
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:1337"
    networks:
      - webnet
  mongo:
    image: mongo:latest
    container-name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
networks:
  webnet:
